apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - rbac.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -in-place-scaling=true
    target:
      kind: DaemonSet
